### ISSUE TITLE
Approve DAI and LINK spending on init

### ISSUE THREAD

**Issue by imollov** [hackbg/chainlink-makerdao-keepers#25]
Instead of calling approve for DAI and LINK in the top up function

Ex: https://github.com/beefyfinance/beefy-contracts/blob/master/contracts/BIFI/keepers/contracts/UpkeepRefunder.sol#L150

**Comment by mradkov** [comment]
Infinite approvals are considered unsafe though. Keep in mind :)

**Comment by imollov** [comment]
Resolved in #65
